In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

# missing values occurs when data is not collected properly or the values are missing they are are represented as:
# None a python object used to represent missing value in object-type arrays
# Nan a special floating point value from numpy acknowledged by all system that uses IEE

In [3]:
# isnull(): returns a dataframe or boolean value where true represent missing data (NAN), used to find anf fill missing data 

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}

df = pd.DataFrame(d)
mv = df.isnull()
display(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [6]:
df = pd.read_csv(r"C:\Users\HP\Downloads\employees.csv")
df.to_csv('employee.csv', index=False)
print(df.head())

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team
0              True        Marketing
1              True              NaN
2             False          Finance
3              True          Finance
4              True  Client Services

In [3]:
df = pd.read_csv('employee.csv')
mv = df.isnull()
display(mv)
print()

bool_series = pd.isnull(df['Gender'])
missing_gender = df[bool_series]
display(missing_gender)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,True,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
22,Joshua,NaN,3/8/2012,1:58 AM,90816,18.816,True,Client Services
27,Scott,NaN,7/11/1991,6:58 PM,122367,5.218,False,Legal
31,Joyce,NaN,2/20/2005,2:40 PM,88657,12.752,False,Product
41,Christine,NaN,6/28/2015,1:08 AM,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
961,Antonio,NaN,6/18/1989,9:37 PM,103050,3.050,False,Legal
972,Victor,NaN,7/28/2006,2:49 PM,76381,11.159,True,Sales
985,Stephen,NaN,7/10/1983,8:10 PM,85668,1.909,False,Legal
989,Justin,NaN,2/10/1991,4:58 PM,38344,3.794,False,Legal
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution

In [12]:
# isna return a dataframe of boolean value where true means missing data (NAN), used to detect missing value like isnull()

data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)
mv = df.isna()
display(mv)

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [13]:
# notnull function that returns a dataframe of boolean value where true means it has a valid value useful for focusing on rows with valid data

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
nmv = df.notnull()
display(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [4]:
data = pd.read_csv('employee.csv')
bool_series = pd.notnull(data['Gender'])
check_g  = data[bool_series]
display(check_g)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [15]:
# fillna is used to replace missing value (NAN) with a given value

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [18]:
# ffill forward fill is used to fill nan with previous value 

df.ffill()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [19]:
# bfill backward fill is used to fill nan with next value 

df.bfill()

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [24]:
data = pd.read_csv('employee.csv')
display(data[10:25])
print()

data['Gender'] = data['Gender'].fillna('No Gender')
display(data[10:25])

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,NaN,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No Gender,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,No Gender,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

In [25]:
# replace can be used to replace nan value with specific value 

data = pd.read_csv('employee.csv')
display(data[10:25])
print()

data = data.replace(to_replace=np.nan, value=-1)
display(data[10:25])

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,NaN,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,-1
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,-1,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,-1,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,-1,Male,6/14/2012,4:19 PM,125792,5.042,-1,-1
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

In [26]:
# The interpolate() function fills missing values using interpolation techniques such as the linear method.
   
df = pd.DataFrame({"A": [12, 4, 5, None, 1], 
                   "B": [None, 2, 54, 3, None], 
                   "C": [20, 16, None, 3, 8], 
                   "D": [14, 3, None, None, 6]})  
print(df)
print()

df.interpolate(method='linear', limit_direction='forward')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

In [30]:
# dropna is used to drop rows or columns with nan

dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
display(df.dropna())
print()

# using how can be used to drop rows 
display(df.dropna(how='all'))
print()

# to drop column with atleast one null values 
display(df.dropna(axis=1))
print()

# to drop row with missing values
display(df.dropna(axis=0))

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

   Third Score
0           52
1           40
2           80
3           98

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [5]:
df = pd.read_csv('employee.csv')
display(df.dropna(axis=0, how='any'))
print()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [32]:
# DataFrame.drop_duplicates(subset=None, keep='first', inplace=False)

data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print()

cleaned = df.drop_duplicates()
print(cleaned)

Original DataFrame:
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [37]:
data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}

df = pd.DataFrame(data)
clean_name = df.drop_duplicates(subset=['Name'])
print(clean_name)
print()

clean_name2 = df.drop_duplicates(keep='last')
print(clean_name2)
print()

remove_all =  df.drop_duplicates(keep=False)
print(remove_all)
print()

df.drop_duplicates(inplace=True)
print(df)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

    Name  Age     City
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

    Name  Age     City
1    Bob   30       LA
3  David   40  Chicago

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [38]:
data = {
    "Name": ["Alice", "Bob", "Alice", "David", "Bob"],
    "Age": [25, 30, 25, 40, 30],
    "City": ["NY", "LA", "NY", "Chicago", "LA"]
}

df = pd.DataFrame(data)
print(df)
print()

df_cleaned = df.drop_duplicates(subset=["Name", "City"]) # for columns 

print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago
4    Bob   30       LA

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [44]:
# ensuring the column in a data has the corrcet datatype we use astype()

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000],
       'Join Date': ['2021-01-01', '2020-05-22', '2022-03-15', '2021-07-30', '2020-11-11']}

df = pd.DataFrame(data)
df['Age'] = df['Age'].astype(float)
print(df.dtypes)
print()

df['Join Date'] = pd.to_datetime(df['Join Date']) # pd.to_datetime()converting date stored as a string to date
print(df.dtypes)
print()

df = df.astype({'Age':'float64', 'Salary':'str'})
print(df.dtypes)

Name          object
Age          float64
Gender        object
Salary         int64
Join Date     object
dtype: object

Name                 object
Age                 float64
Gender               object
Salary                int64
Join Date    datetime64[ns]
dtype: object

Name                 object
Age                 float64
Gender               object
Salary               object
Join Date    datetime64[ns]
dtype: object

In [48]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
display(df)

nan_value = float("NaN")
df.replace("", nan_value, inplace=True)
df.dropna(how='all', axis=1, inplace=True)

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

C:\Users\HP\AppData\Local\Temp\ipykernel_24412\3588468072.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("", nan_value, inplace=True)

  FirstName  Age
0     Vipul    0
1    Ashish    0
2     Milan    0

In [49]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
display(df)

nan_value = float("NaN")
df.replace(0, nan_value, inplace=True)
df.dropna(how='all', axis=1, inplace=True)

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender
0     Vipul
1    Ashish
2     Milan

In [50]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan
display(df)

nan_value = float("NaN")
df.replace(0, nan_value, inplace=True)
df.replace("", nan_value, inplace=True)

df.dropna(how='all', axis=1, inplace=True)

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

C:\Users\HP\AppData\Local\Temp\ipykernel_24412\1041238043.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("", nan_value, inplace=True)

  FirstName
0     Vipul
1    Ashish
2     Milan

In [53]:
# String manipulation refers to cleaning, transforming, and processing text data so it becomes suitable for analysis. 

data = { 'Name': ['Lukas', 'Sofia', 'Hiroshi', 'Marta', 'Yannis', np.nan, 'Elena'],
         'City': ['Berlin', 'Madrid', 'Tokyo', 'Warsaw', 'Athens', 'Oslo', 'Lisbon'] }

df = pd.DataFrame(data)
print(df.dtypes)
print()

df.astype(str)
print(df.dtypes)

Name    object
City    object
dtype: object

Name    object
City    object
dtype: object

In [57]:
df['Name'] = df['Name'].str.lower()
print(df)
print()

df['City'] = df['City'].str.upper()
print(df)
print()

      Name    City
0    lukas  Berlin
1    sofia  Madrid
2  hiroshi   Tokyo
3    marta  Warsaw
4   yannis  Athens
5      NaN    Oslo
6    elena  Lisbon

      Name    City
0    lukas  BERLIN
1    sofia  MADRID
2  hiroshi   TOKYO
3    marta  WARSAW
4   yannis  ATHENS
5      NaN    OSLO
6    elena  LISBON

In [64]:
print(df['Name'].str.strip())
print()

print(df['Name'].str.split('a'))
print()

print(df['Name'].str.len())
print()

print(df['Name'].str.cat(sep=', '))
print()

print(df['City'].str.get_dummies())
print()

print(df['Name'].str.startswith('E'))
print()

print(df['Name'].str.endswith('a'))
print()

print(df['Name'].str.replace('Elena', 'Emily'))
print()

0      lukas
1      sofia
2    hiroshi
3      marta
4     yannis
5        NaN
6      elena
Name: Name, dtype: object

0     [luk, s]
1     [sofi, ]
2    [hiroshi]
3    [m, rt, ]
4    [y, nnis]
5          NaN
6     [elen, ]
Name: Name, dtype: object

0    5.0
1    5.0
2    7.0
3    5.0
4    6.0
5    NaN
6    5.0
Name: Name, dtype: float64

lukas, sofia, hiroshi, marta, yannis, elena

   ATHENS  BERLIN  LISBON  MADRID  OSLO  TOKYO  WARSAW
0       0       1       0       0     0      0       0
1       0       0       0       1     0      0       0
2       0       0       0       0     0      1       0
3       0       0       0       0     0      0       1
4       1       0       0       0     0      0       0
5       0       0       0       0     1      0       0
6       0       0       1       0     0      0       0

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Name, dtype: object

0    False
1     True
2    False
3     True
4    False
5      NaN
6     True
Name: Name, dtype: object

0      lukas
1      sofia
2    hiroshi
3      marta
4     yannis
5        NaN
6      elena
Name: Name, dtype: object

In [65]:
print(df['Name'].str.repeat(2))
print()

print(df['Name'].str.count('a'))
print()

print(df['Name'].str.find('a'))
print()

print(df['Name'].str.findall('a'))
print()

print(df['Name'].str.islower())
print()

print(df['Name'].str.isupper())
print()

print(df['Name'].str.isnumeric())
print()

print(df['Name'].str.swapcase())
print()

0        lukaslukas
1        sofiasofia
2    hiroshihiroshi
3        martamarta
4      yannisyannis
5               NaN
6        elenaelena
Name: Name, dtype: object

0    1.0
1    1.0
2    0.0
3    2.0
4    1.0
5    NaN
6    1.0
Name: Name, dtype: float64

0    3.0
1    4.0
2   -1.0
3    1.0
4    1.0
5    NaN
6    4.0
Name: Name, dtype: float64

0       [a]
1       [a]
2        []
3    [a, a]
4       [a]
5       NaN
6       [a]
Name: Name, dtype: object

0    True
1    True
2    True
3    True
4    True
5     NaN
6    True
Name: Name, dtype: object

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Name, dtype: object

0    False
1    False
2    False
3    False
4    False
5      NaN
6    False
Name: Name, dtype: object

0      LUKAS
1      SOFIA
2    HIROSHI
3      MARTA
4     YANNIS
5        NaN
6      ELENA
Name: Name, dtype: object

In [66]:
# identifying mixed data types 

df = pd.DataFrame( [['tom', 10], ['nick', '15'], ['juli', 14.8]], columns=['Name', 'Age'])
for col in df.columns :
    print(col, ':', pd.api.types.infer_dtype(df[col]))

Name : string
Age : mixed-integer

In [68]:
df = pd.DataFrame( [['tom', 10], ['nick', '15'], ['juli', 14.8]], columns=['Name', 'Age'])
df[col] = df[col].astype(int)

for col in df.columns:
    print(col, ':', pd.api.types.infer_dtype(df[col]))

Name : string
Age : integer

In [71]:
data_frame = pd.DataFrame([
    ['tom', 10],
    ['nick', '15'],
    ['juli', 14.8]
], columns=['Name', 'Age'])

for column in data_frame.columns:
    data_frame[column] = pd.to_numeric(data_frame[column], errors='coerce')

for column in data_frame.columns:
    print(pd.api.types.infer_dtype(data_frame[column]))

floating
floating