In [1]:
# csv comma seperated value files that allow storage of tabular data 
# DataFrame is a data structure that allows analysis reading and maipulating of tabular data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# d.read_csv(filepath_or_buffer, sep=' ,' , header='infer',  index_col=None, usecols=None, engine=None, skiprows=None, nrows=None)

data = pd.read_csv(r"C:\Users\HP\AppData\people_data.csv")
data

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [4]:
data.to_csv("pmini.csv" index=False)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (513042541.py, line 1)

In [5]:
dt = pd.read_csv('pmini.csv', usecols=['First Name', 'Email']) # usecols to bring out the column needed 
print(dt)
print()

dt2 = pd.read_csv('pmini.csv', index_col=['First Name']) # index column is used to set index 
print(dt2)
print()

dt3 = pd.read_csv('pmini.csv', na_values=['N/A', 'Unknown'])
dt3 = dt3.reset_index(drop=True)
print(dt3)

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

            Unnamed: 0 Last Name     Sex                       Email  \
First Name
Shelby               0   Terrell    Male        elijah57@example.net
Phillip              1   Summers  Female       bethany14@example.com
Kristine             2    Travis    Male       bthompson@example.com
Yesenia              3  Martinez    Male   kaitlinkaiser@example.com
Lori                 4      Todd    Male  buchananmanuel@example.net

           Date of birth           Job Title
First Name
Shelby        1945-10-26     Games developer
Phillip       1910-03-24      Phytotherapist
Kristine      1992-07-02           Homeopath
Yesenia       2017-08-03   Market researcher
Lori          1938-12-01  Veterinary surgeon

   Unnamed: 0 First Name Last Name     Sex                       Email  \
0           0     Shelby   Terrell    Male        elijah57@example.net
1           1    Phillip   Summers  Female       bethany14@example.com
2           2   Kristine    Travis    Male       bthompson@example.com
3           3    Yesenia  Martinez    Male   kaitlinkaiser@example.com
4           4       Lori      Todd    Male  buchananmanuel@example.net

  Date of birth           Job Title
0    1945-10-26     Games developer
1    1910-03-24      Phytotherapist
2    1992-07-02           Homeopath
3    2017-08-03   Market researcher
4    1938-12-01  Veterinary surgeon

In [7]:
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open('sample.csv', 'w') as file:
    file.write(data)

print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4

In [9]:
df = pd.read_csv('sample.csv', sep='[:, |_]', engine='python')
display(df)
print()

df2 = pd.read_csv('sample.csv', sep='[:, |_]', engine='python', nrows=4)
display(df2)

,totalbill,tip,Unnamed: 2,sex,smoker,Unnamed: 5,day,time,Unnamed: 8,size
16.99,NaN,1.01,Female,No,NaN,Sun,NaN,Dinner,NaN,2.0
10.34,NaN,1.66,NaN,Male,NaN,No,Sun,Dinner,NaN,3.0
21.01,3.50,Male,NaN,No,Sun,NaN,Dinner,NaN,3.0,NaN
23.68,NaN,3.31,NaN,Male,No,NaN,Sun,Dinner,NaN,2.0
24.59,3.61,NaN,Female,No,NaN,Sun,NaN,Dinner,NaN,4.0
25.29,NaN,4.71,Male,NaN,No,Sun,NaN,Dinner,NaN,4.0

,totalbill,tip,Unnamed: 2,sex,smoker,Unnamed: 5,day,time,Unnamed: 8,size
16.99,NaN,1.01,Female,No,NaN,Sun,NaN,Dinner,NaN,2.0
10.34,NaN,1.66,NaN,Male,NaN,No,Sun,Dinner,NaN,3.0
21.01,3.5,Male,NaN,No,Sun,NaN,Dinner,NaN,3.0,NaN
23.68,NaN,3.31,NaN,Male,No,NaN,Sun,Dinner,NaN,2.0

In [11]:
df = pd.read_csv('pmini.csv')
print("Dataset before skipping rows: ")
print(df2)
print()

df2 = pd.read_csv('pmini.csv', skiprows=[4, 5])
print("Dataset After skipping rows: ")
print(df2)

Dataset After skipping rows:
       totalbill   tip Unnamed: 2   sex smoker Unnamed: 5     day    time  \
16.99        NaN  1.01     Female    No    NaN        Sun     NaN  Dinner
10.34        NaN  1.66        NaN  Male    NaN         No     Sun  Dinner
21.01        3.5  Male        NaN    No    Sun        NaN  Dinner     NaN
23.68        NaN  3.31        NaN  Male     No        NaN     Sun  Dinner

       Unnamed: 8  size
16.99         NaN   2.0
10.34         NaN   3.0
21.01         3.0   NaN
23.68         NaN   2.0

Dataset After skipping rows:
   Unnamed: 0 First Name Last Name     Sex                  Email  \
0           0     Shelby   Terrell    Male   elijah57@example.net
1           1    Phillip   Summers  Female  bethany14@example.com
2           2   Kristine    Travis    Male  bthompson@example.com

  Date of birth        Job Title
0    1945-10-26  Games developer
1    1910-03-24   Phytotherapist
2    1992-07-02        Homeopath

In [12]:
df = pd.read_csv('pmini.csv', parse_dates=['Date of birth'])
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     5 non-null      int64
 1   First Name     5 non-null      object
 2   Last Name      5 non-null      object
 3   Sex            5 non-null      object
 4   Email          5 non-null      object
 5   Date of birth  5 non-null      datetime64[ns]
 6   Job Title      5 non-null      object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 412.0+ bytes
None

In [13]:
url = "https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv"
df = pd.read_csv(url)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [20]:
nme = ["Aparna", "Pankaj", "Sudhir", "Geeku"]
deg = ["MBA", "BCA", "M.Tech", "MBA"]
scr = [90, 40, 80, 98]

data = {'Name': nme, 'Degree':deg, 'Score':scr}
df = pd.DataFrame(data)
df.to_csv('file1.csv')
display(df)
print()

df.to_csv('file.csv', header=False, index=False)
df2 = pd.read_csv("file.csv", header=None)
df2

     Name  Degree  Score
0  Aparna     MBA     90
1  Pankaj     BCA     40
2  Sudhir  M.Tech     80
3   Geeku     MBA     98

        0       1   2
0  Aparna     MBA  90
1  Pankaj     BCA  40
2  Sudhir  M.Tech  80
3   Geeku     MBA  98

In [22]:
users = {
    "Name": ["Amit", "Cody", "Drew"],
    "Age": [20, 21, 25]
}

df = pd.DataFrame(users)
df.to_csv('user.csv', sep='\t', index=False)

new_df = pd.read_csv('user.csv', sep='\t')
new_df

   Name  Age
0  Amit   20
1  Cody   21
2  Drew   25

In [29]:
scores = {'Name': ['a', 'b', 'c', 'd'],
          'Score': [90, 80, 95, 20]}

df = pd.DataFrame(scores)
df.to_csv('yours.csv', index=False, header=False)

new = pd.read_csv('yours.csv', header=None)
new

   0   1
0  a  90
1  b  80
2  c  95
3  d  20

In [2]:
scores = {'Name': ['a', 'b', 'c', 'd'],
          'Score': [90, 80, 95, 20]}

df = pd.DataFrame(scores)
df.to_csv('your.csv', columns = ['Name'], index=False, header=False)

new = pd.read_csv('your.csv', header=None)
display(new)
print()

df.to_csv('yours.csv', columns = ['Name'], index=False, header=False, na_rep='nothing')
new2 = pd.read_csv('yours.csv', header=None )
display(new2)

   0
0  a
1  b
2  c
3  d

   0
0  a
1  b
2  c
3  d

In [3]:
# json is a popular way to store and exchange data especially used in web APIs and configuration files

data = [
    {"id": 1, "name": "Alice", "age": 25},
    {"id": 2, "name": "Bob", "age": 30},
    {"id": 3, "name": "Charlie", "age": 22}
]

df = pd.DataFrame(data)
df.to_json('data.json')


with open('data.json', 'r') as file:
    print(file.read())
print()

new = pd.read_json('data.json')
new

{"id":{"0":1,"1":2,"2":3},"name":{"0":"Alice","1":"Bob","2":"Charlie"},"age":{"0":25,"1":30,"2":22}}

   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   22

In [39]:
import json
data = {"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60},
        "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}}

j_data = json.dumps(data)
print(j_data)
print()

j_norm = pd.json_normalize(json.loads(j_data))
j_norm

{"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60}, "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}}

,One.0,One.1,One.2,One.3,One.4,One.5,Two.0,Two.1,Two.2,Two.3,Two.4,Two.5
0,60,60,60,45,45,60,110,117,103,109,117,102

In [43]:
df = pd.DataFrame(data)
display(df)

   One  Two
0   60  110
1   60  117
2   60  103
3   45  109
4   45  117
5   60  102

In [45]:
dt = [['a', 'b'], ['c', 'd']]
df = pd.DataFrame(dt, index=['row 1', 'row 2'], columns=['col 1', 'col 2'])

print(df.to_json(orient='split'))
print(df.to_json(orient='index'))

{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}
{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}

In [4]:
import requests

url = 'https://jsonplaceholder.typicode.com/posts'
res = requests.get(url)

data = pd.json_normalize(res.json())
display(data)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [51]:
import json

sample_data = {
    "programs": [
        {
            "id": "001",
            "orchestra": "NYC Philharmonic",
            "season": "2023-24",
            "concerts": [
                {"date": "2023-10-01", "location": "Lincoln Center"},
                {"date": "2023-10-05", "location": "Carnegie Hall"}
            ]
        },
        {
            "id": "002",
            "orchestra": "NYC Philharmonic",
            "season": "2023-24",
            "concerts": [
                {"date": "2023-11-12", "location": "Lincoln Center"}
            ]
        }
    ]
}

with open("raw_nyc.json", "w") as f:
    json.dump(sample_data, f, indent=4)

print("File created successfully!")

File created successfully!

In [53]:
from pandas import json_normalize

with open("raw_nyc.json") as f:
    d = json.load(f)

nyc = json_normalize(d["programs"])
print(nyc.head())

    id         orchestra   season  \
0  001  NYC Philharmonic  2023-24
1  002  NYC Philharmonic  2023-24

                                            concerts
0  [{'date': '2023-10-01', 'location': 'Lincoln C...
1  [{'date': '2023-11-12', 'location': 'Lincoln C...

In [55]:
df = pd.DataFrame([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']],
                  index=['row 1', 'row 2', 'row 3'],
                  columns=['col 1', 'col 2', 'col 3'])

df.to_json('file.json', orient='split', compression='infer', index=True)
print(df)
print()

df = pd.read_json('file.json', orient='split', compression='infer')
display(df)

      col 1 col 2 col 3
row 1     a     b     c
row 2     d     e     f
row 3     g     h     i

      col 1 col 2 col 3
row 1     a     b     c
row 2     d     e     f
row 3     g     h     i

In [57]:
df = pd.DataFrame(data=[
    ['15135', 'Alex', '25/4/2014'],
    ['23515', 'Bob', '26/8/2018'],
    ['31313', 'Martha', '18/1/2019'],
    ['55665', 'Alen', '5/5/2020'],
    ['63513', 'Maria', '9/12/2020']],
    columns=['ID', 'NAME', 'DATE OF JOINING'])

df.to_json('file3.json', orient='split', compression='infer')
df2 = pd.read_json('file3.json', orient='split', compression='infer')

print(df)
print()

print(df2)

      ID    NAME DATE OF JOINING
0  15135    Alex       25/4/2014
1  23515     Bob       26/8/2018
2  31313  Martha       18/1/2019
3  55665    Alen        5/5/2020
4  63513   Maria       9/12/2020

      ID    NAME DATE OF JOINING
0  15135    Alex       25/4/2014
1  23515     Bob       26/8/2018
2  31313  Martha       18/1/2019
3  55665    Alen        5/5/2020
4  63513   Maria       9/12/2020

In [ ]:
df = pd.read_csv("gfg.txt", sep=" ", header=None, 
                 names=["Team1", "Team2"])

print(df)