In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [7]:

data = {'Name': ['Jake', 'Eve', 'Charlie'],
        'Age': [ 22, 35, 28],
        'Gender': [ 'Male', 'Female', 'Male'],
        'Salary': [40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df.index)
print(df)
print()

res = df.set_index('Name') # set_index() method is used to change the index of a DataFrame by setting one or more columns as the new index.
print(res)
print()

res2 = df.reset_index(drop=True) # reset_index() will convert the current index into a regular column and create a new default index.
print(res2)

RangeIndex(start=0, stop=3, step=1)
      Name  Age  Gender  Salary
0     Jake   22    Male   40000
1      Eve   35  Female   70000
2  Charlie   28    Male   48000

         Age  Gender  Salary
Name
Jake      22    Male   40000
Eve       35  Female   70000
Charlie   28    Male   48000

      Name  Age  Gender  Salary
0     Jake   22    Male   40000
1      Eve   35  Female   70000
2  Charlie   28    Male   48000

In [11]:
# loc method allows us to access rows and columns in a dataframe using their label names 

data = {'age': [25, 30], 'city': ['NY', 'LA']}
df = pd.DataFrame(data, index=['Alice', 'Bob'])

print(df.loc['Alice'])
print()

print(df['age']) # returns a series 
print()

print(df[['age']]) # returns a dataframe

age     25
city    NY
Name: Alice, dtype: object

Alice    25
Bob      30
Name: age, dtype: int64

       age
Alice   25
Bob     30

In [16]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
print()

age_col = df[['Age']]
print(age_col)
print()

# To access specific rows in a DataFrame, you can use iloc (for positional indexing)
second_row = df.iloc[1]
print(second_row)
print()

subset = df.loc[0:2, ['Name', 'Age']]
print(subset)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

   Age
0   25
1   30
2   22
3   35
4   28

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

    Name  Age
0   John   25
1  Alice   30
2    Bob   22

In [19]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
print()

filtered = df[df['Age'] > 25]
print(filtered)
print()

filt = df[(df['Age'] > 25) & (df['Age'] <35)]
print(filt)
print()

# at[] is used to access a specific cell

salary_at_2 = df.at[2, 'Salary']
print(salary_at_2)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
4  Charlie   28    Male   48000

40000

In [23]:
# [] operator is used for indexing in pandas allowing row or column selection based on conditions

df = pd.read_csv(r"C:\Users\HP\Downloads\nba.csv")
df.to_csv('nba.csv', index=False)

In [10]:
df = pd.read_csv('nba.csv', index_col='Name')
print(df.head(5))
print()

firs = df[['Age']]
print(firs.head(5))
print()

sec = df[['Age', 'College', 'Salary']]
print(sec.head(5))

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0

                Age
Name
Avery Bradley  25.0
Jae Crowder    25.0
John Holland   27.0
R.J. Hunter    22.0
Jonas Jerebko  29.0

                Age            College     Salary
Name
Avery Bradley  25.0              Texas  7730337.0
Jae Crowder    25.0          Marquette  6796117.0
John Holland   27.0  Boston University        NaN
R.J. Hunter    22.0      Georgia State  1148640.0
Jonas Jerebko  29.0                NaN  5000000.0

In [3]:
df = pd.read_csv('nba.csv', index_col= 'Name')
res = df.loc[['Avery Bradley']]
res2 = df.loc['Avery Bradley']

print(res)
print()

print(res2)
print()

rows = df.loc[["Avery Bradley", "R.J. Hunter"]]
print(rows)
print()

selection = df.loc[["Avery Bradley", "R.J. Hunter"], ["Team", "Number", "Position"]]
print(selection)
print()

all_rows = df.loc[:, ["Team", "Number", "Position"]]
print(all_rows.head(5))
print()

rows2 = df.iloc[[1, 3, 5, 7]]
print(rows2)
print()

row_col = df.iloc[[2, 7, 11, 15], [0, 2, 4, 6]]
print(row_col)
print()

select = df.iloc[:, [1, 3, 5]]
print(select.head(5))

                         Team  Number Position   Age Height  Weight College  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   Texas

                  Salary
Name
Avery Bradley  7730337.0

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0

                     College     Salary
Name
Avery Bradley          Texas  7730337.0
R.J. Hunter    Georgia State  1148640.0

                         Team  Number Position
Name
Avery Bradley  Boston Celtics     0.0       PG
R.J. Hunter    Boston Celtics    28.0       SG

                         Team  Number Position
Name
Avery Bradley  Boston Celtics     0.0       PG
Jae Crowder    Boston Celtics    99.0       SF
John Holland   Boston Celtics    30.0       SG
R.J. Hunter    Boston Celtics    28.0       SG
Jonas Jerebko  Boston Celtics     8.0       PF

                        Team  Number Position   Age Height  Weight  \
Name
Jae Crowder   Boston Celtics    99.0       SF  25.0    6-6   235.0
R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5   185.0
Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0

                    College      Salary
Name
Jae Crowder       Marquette   6796117.0
R.J. Hunter   Georgia State   1148640.0
Amir Johnson            NaN  12000000.0
Kelly Olynyk        Gonzaga   2165160.0

                            Team Position Height            College
Name
John Holland      Boston Celtics       SG    6-5  Boston University
Kelly Olynyk      Boston Celtics        C    7-0            Gonzaga
Isaiah Thomas     Boston Celtics       PG    5-9         Washington
Bojan Bogdanovic   Brooklyn Nets       SG    6-8                NaN

               Number   Age  Weight
Name
Avery Bradley     0.0  25.0   180.0
Jae Crowder      99.0  25.0   235.0
John Holland     30.0  27.0   205.0
R.J. Hunter      28.0  22.0   185.0
Jonas Jerebko     8.0  29.0   231.0

In [6]:
df = pd.read_csv('nba.csv', index_col= 'Name')

print(df.head(6)) # head returns the first n rows of a data
print(df.tail(6)) # tail returns the last n rows of a data
print()

value = df.at["Avery Bradley", "Age"]
print(value)
print()

res = df.query("Age > 25 and College == 'Duke'")
print(res)
print()

res2 = df[(df['Age'] > 25) & (df['College'] == 'Kentucky')]
print(res2)

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0

                         College      Salary
Name
Avery Bradley              Texas   7730337.0
Jae Crowder            Marquette   6796117.0
John Holland   Boston University         NaN
R.J. Hunter        Georgia State   1148640.0
Jonas Jerebko                NaN   5000000.0
Amir Johnson                 NaN  12000000.0
                   Team  Number Position   Age Height  Weight   College  \
Name
Trey Lyles    Utah Jazz    41.0       PF  20.0   6-10   234.0  Kentucky
Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0    Butler
Raul Neto     Utah Jazz    25.0       PG  24.0    6-1   179.0       NaN
Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0       NaN
Jeff Withey   Utah Jazz    24.0        C  26.0    7-0   231.0    Kansas
NaN                 NaN     NaN      NaN   NaN    NaN     NaN       NaN

                 Salary
Name
Trey Lyles    2239800.0
Shelvin Mack  2433333.0
Raul Neto      900000.0
Tibor Pleiss  2900000.0
Jeff Withey    947276.0
NaN                 NaN

25.0

                                    Team  Number Position   Age Height  \
Name
Lance Thomas             New York Knicks    42.0       SF  28.0    6-8
Elton Brand           Philadelphia 76ers    42.0       PF  37.0    6-9
JJ Redick           Los Angeles Clippers     4.0       SG  31.0    6-4
Mike Dunleavy              Chicago Bulls    34.0       SG  35.0    6-9
Dahntay Jones        Cleveland Cavaliers    30.0       SG  35.0    6-6
Miles Plumlee            Milwaukee Bucks    18.0        C  27.0   6-11
Luol Deng                     Miami Heat     9.0       SF  31.0    6-9
Josh McRoberts                Miami Heat     4.0       PF  29.0   6-10
Kyle Singler       Oklahoma City Thunder     5.0       SF  28.0    6-8
Gerald Henderson  Portland Trail Blazers     9.0       SG  28.0    6-5
Mason Plumlee     Portland Trail Blazers    24.0        C  26.0   6-11

                  Weight College      Salary
Name
Lance Thomas       235.0    Duke   1636842.0
Elton Brand        254.0    Duke         NaN
JJ Redick          190.0    Duke   7085000.0
Mike Dunleavy      230.0    Duke   4500000.0
Dahntay Jones      225.0    Duke         NaN
Miles Plumlee      249.0    Duke   2109294.0
Luol Deng          220.0    Duke  10151612.0
Josh McRoberts     240.0    Duke   5543725.0
Kyle Singler       228.0    Duke   4500000.0
Gerald Henderson   215.0    Duke   6000000.0
Mason Plumlee      235.0    Duke   1415520.0

                                     Team  Number Position   Age Height  \
Name
Patrick Patterson         Toronto Raptors    54.0       PF  27.0    6-9
Eric Bledsoe                 Phoenix Suns     2.0       PG  26.0    6-1
Rajon Rondo              Sacramento Kings     9.0       PG  30.0    6-1
Jodie Meeks               Detroit Pistons    20.0       SG  28.0    6-4
Tayshaun Prince    Minnesota Timberwolves    12.0       SF  36.0    6-9
Nazr Mohammed       Oklahoma City Thunder    13.0        C  38.0   6-10

                   Weight   College      Salary
Name
Patrick Patterson   235.0  Kentucky   6268675.0
Eric Bledsoe        190.0  Kentucky  13500000.0
Rajon Rondo         186.0  Kentucky   9500000.0
Jodie Meeks         210.0  Kentucky   6270000.0
Tayshaun Prince     212.0  Kentucky    947276.0
Nazr Mohammed       250.0  Kentucky    222888.0

In [40]:
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns = ['Name', 'Age', 'Rating', 'Votes'])
print(df)
print()

res = df.iloc[1:4]
print(res)
print()

res2 = df.iloc[:, 0:2]
print(res2)
print()

row2 = df.iloc[2, 3]
print(row2)
print()

fil = df[df['Age'] > 35]
print(fil)
print()

fil2 = df[(df['Age'] > 32) & (df['Age'] < 42)]
print(fil2)

            Name  Age  Rating    Votes
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

            Name  Age  Rating    Votes
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

8428000

            Name  Age  Rating    Votes
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
4        C.Gayle   40     100  4528000
6     K.Peterson   42      85  2528000

            Name  Age  Rating    Votes
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000

In [43]:
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns = ['Name', 'Age', 'Rating', 'Votes'])
df.set_index('Name', inplace=True)

custom = df.loc['A.B.D Villers':'S.Smith']
print(custom)

value = df.loc['V.Kohli', 'Votes']
print("\nValue of the Specific Cell (V.Kohli, Salary):", value)

               Age  Rating    Votes
Name
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000

Value of the Specific Cell (V.Kohli, Salary): 8428000

In [53]:
dataframe = pd.DataFrame({'Name': ['RACHEL', 'MONICA', 'PHOEBE', 'ROSS', 'CHANDLER', 'JOEY'],
                          'Age': [30, 35, 37, 33, 34, 30],
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY', 'IT', 'ARTIST']})

display(dataframe)
print()

display(dataframe.loc[(dataframe['Salary'] >= 100000) & (dataframe['Age'] < 40) & (dataframe['JOB'].str.startswith('D')), ['Name', 'JOB']])

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

        Name       JOB
0   RACHEL    DESIGNER

In [59]:
df = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ', '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          'Age': [30, 35, 37, 33, 34, 30],
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY', 'IT', 'ARTIST']})

filt = np.where((df['Salary'] >= 100000 )  & (df['Age'] <= 40) & (df['JOB'].str.startswith('D')))
print(filt)
print()

display(df.loc[filt])
print()

display(df.query('Salary  <= 100000 & Age < 40 & JOB.str.startswith("C").values'))
print()

display(df[(df['Salary'] >= 100000 )  & (df['Age'] <= 40) & (df['JOB'].str.startswith('P'))][['Name','Age','Salary']])
print()

(array([0]),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF

         Name  Age  Salary
3    ROSS       33  120000

In [62]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])
df2 = pd.DataFrame (data2, index=[4, 5, 6, 7])

print(df, '\n\n', df2)
print()

frames = [df, df2]
res = pd.concat(frames)
print(res)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [3]:
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])
df2 = pd.DataFrame(data2, index=[2, 4, 6, 7])
print(df, "\n\n", df2)

res = pd.concat([df, df2], axis=1, join='inner')
res
print()

res2 = pd.concat([df, df2], axis=1, sort=False)
res2

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
4    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

In [70]:
# We can ignore the indexes and reset them using the ignore_index argument.

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])
df2 = pd.DataFrame(data2, index=[4, 5, 6, 7])
res = pd.concat([df, df2], ignore_index=True ) 
print(res)
print()

# keys argument is used to retain information about the DataFrame from which each row came from.

frames = [df, df2]
res2 = pd.concat(frames, keys=['x', 'y'])
res2

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
4  Gaurav   22  Allahabad           MCA        NaN  1000.0
5    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 4  Gaurav   22  Allahabad           MCA        NaN  1000.0
  5    Anuj   32    Kannuaj           Phd        NaN  2000.0
  6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [8]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)
frames = [df, s1]
res = pd.concat(frames, axis=1)
res

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

In [78]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons'],}
df = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
res = pd.merge(df, df2, on='key')
res

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [82]:
import pandas as pd

d1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

d2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(d1)
df1 = pd.DataFrame(d2)
print(df, "\n\n", df1)
print()

res = pd.merge(df, df1, on=['key', 'key1'])
print(res)
print()

res2 = pd.merge(df, df1, how='left', on=['key', 'key1'])
print(res2)
print()

res3 = pd.merge(df, df1, how='right', on=['key', 'key1'])
print(res3)
print()

res4 = pd.merge(df, df1, how='outer', on=['key', 'key1'])
print(res4)
print()

res5 = pd.merge(df, df1, how='inner', on=['key', 'key1'])
print(res5)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K2   K0  Gaurav  22.0  Allahabad          Bcom
3  K3   K0     NaN   NaN    Kannuaj        B.hons

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K1   K1  Princi  24.0        NaN           NaN
3  K2   K0  Gaurav  22.0  Allahabad          Bcom
4  K3   K0     NaN   NaN    Kannuaj        B.hons
5  K3   K1    Anuj  32.0        NaN           NaN

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [84]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])
df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])

print(df, "\n\n", df1)
print()

res = df.join(df1)
print(res)
print()

res1 = df.join(df1, how='outer')
print(res1)
print()

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K1  Princi  24.0        NaN           NaN
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

In [85]:
# the on is used to join DataFrames based on a column (rather than the index)

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])
print(df, "\n\n", df1)
print()

res2 = df.join(df1, on='Key')
print(res2)
print()

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

In [87]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav'],
        'Age':[27, 24, 22]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kanpur'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=pd.Index(['K0', 'K1', 'K2'], name='key'))

index = pd.MultiIndex.from_tuples([('K0', 'Y0'), ('K1', 'Y1'),
                                   ('K2', 'Y2'), ('K2', 'Y3')],
                                   names=['key', 'Y'])

df1 = pd.DataFrame(data2, index= index)
print(df, "\n\n", df1)
print()

result = df.join(df1, how='inner')
result

       Name  Age
key
K0      Jai   27
K1   Princi   24
K2   Gaurav   22

           Address Qualification
key Y
K0  Y0  Allahabad           MCA
K1  Y1    Kannuaj           Phd
K2  Y2  Allahabad          Bcom
    Y3     Kanpur        B.hons

          Name  Age    Address Qualification
key Y
K0  Y0     Jai   27  Allahabad           MCA
K1  Y1  Princi   24    Kannuaj           Phd
K2  Y2  Gaurav   22  Allahabad          Bcom
    Y3  Gaurav   22     Kanpur        B.hons

In [92]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)
sort1 = df.sort_values(by='Age')

print(sort1)
print()

sort2 = df.sort_values(by='Age', ascending=False)
print(sort2)
print()

sort3 = df.sort_values(by=['Age', 'Score'])
print(sort3)
print()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [93]:
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)

sorted_df = df_nan.sort_values(by="Age", na_position="first")
print(sorted_df)

      Name   Age
2  Charlie   NaN
1      Bob  22.0
3    David  22.0
0    Alice  28.0

In [94]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

sort_ind = df.sort_index()
print(sort_ind)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [95]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}

df = pd.DataFrame(data)
df_sorted_by_index_desc = df.sort_index(ascending=False)
print(df_sorted_by_index_desc)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

In [98]:
#  QuickSort (kind='quicksort') selects a "pivot" element and partitions the dataset into two halves: one with elements smaller than the pivot 
# and the other with elements greater than the pivot.

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]}
df = pd.DataFrame(data)

res = df.sort_values(by= 'Age', kind='quicksort')
print(res)
print()

res2 = df.sort_values(by= 'Age', kind='mergesort') # Divides the dataset into smaller subarrays, sorts them and then merges them back together in sorted order.
print(res2)
print()

res3 = df.sort_values(by= 'Age', kind='heapsort')
print(res3) #  It is another comparison-based sorting algorithm that builds a heap data structure to systematically extract the largest 
# or smallest element and reorder the dataset.
print()

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
0    Alice   28     85
4      Eve   28     88

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
0    Alice   28     85
4      Eve   28     88

      Name  Age  Score
1      Bob   22     90
3    David   22     80
2  Charlie   25     95
4      Eve   28     88
0    Alice   28     85

In [99]:
# custom sorting logic using the key parameter is useful when we need to sort strings in a specific way such as ignoring case sensitivity.

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [28, 22, 25, 22, 28],
    "Score": [85, 90, 95, 80, 88]}
df = pd.DataFrame(data)

sorted_df = df.sort_values(by='Name', key=lambda col: col.str.lower())
print(sorted_df)

      Name  Age  Score
0    Alice   28     85
1      Bob   22     90
2  Charlie   25     95
3    David   22     80
4      Eve   28     88

In [10]:
# A pivot table is a statistical table that summarizes a substantial table like a big dataset

df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana', 'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})

df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

In [11]:
pivot = df.pivot_table(index=['Product'], values=['Amount'], aggfunc='sum')
print(pivot)
print()

pivot2 = df.pivot_table(index=['Category'], values=['Amount'], aggfunc='sum')
print(pivot2)
print()

pivot3 = df.pivot_table(index=['Product', 'Category'], values=['Amount'], aggfunc='sum')
print(pivot3)

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

           Amount
Category
Fruit        1701
Vegetable    1197

                    Amount
Product  Category
Banana   Fruit        1091
Beans    Vegetable     626
Broccoli Vegetable     301
Carrots  Vegetable     270
Orange   Fruit         610

In [12]:
# {'mean', 'min'} will get median, mean and minimum of sales respectively
pivot = df.pivot_table(index=['Category'], values=['Amount'], aggfunc={'median', 'mean', 'min'})
print(pivot)
print()

pivot2 = df.pivot_table(index=['Product'], values=['Amount'], aggfunc={'median', 'mean', 'min'})
print(pivot2)

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

              Amount
                mean median  min
Product
Banana    363.666667  384.0   90
Beans     626.000000  626.0  626
Broccoli  150.500000  150.5   62
Carrots   270.000000  270.0  270
Orange    610.000000  610.0  610